### PR TITLE
Commented out addition of code to turn off UseSpericalConeSearch when…

### PR DESCRIPTION
**Pull request by elitemn**
… VR device is not present. fixes issue #80.

### CODE REVIEW

**Comment by elitemn** [comment]
Yes indeed, I knew you must have done that for a reason. Your solution works with the HoloLens emulator as well, but I can't help but wonder if we should be setting the if statement to phone device rather than "if VR device not present" and if "Not in Unity_Editor". What about something like "If device = mobile" or "screensize < x" then set UseSphericalConeSearch = false.  It seems to me that the "UseSphericalConeSearch = false" should only be set when in a small screen, am I thinking about that right?

**Comment by timGerken** [comment]
I don’t think it is just a resolution thing. My phone’s resolution is 1440x2560 (portrait) which is higher than my desktop (1920x1200) or my original Surface Pro (1920x1080). I think we might need a “PlatformManager” class attached somewhere to the CoreSystems.unity scene that knows how to do “the right things” for various resolutions and form factors. I haven’t fully fleshed out exactly what that might look like, but it would be useful to have a GitHub issue to track against. There are also probably some open issues that would fold into it.

**Comment by elitemn** [comment]
Agreed. I'll, open one.

**Comment by timGerken** [comment]
can you update this PR with the fix cited above?

**Pull request merged**
