### PR TITLE
Added Point Of Interest Billboard Creation Utility

### PR DESCRIPTION
**Pull request by elitemn**
Simple utility, quick and dirty. Let me know your thoughts.

Simple windows form utility, just build and run from VS or deploy it locally from the GE_POIMaker project. This requires the Orbitron font installed as mentioned in the readme and in the application itself. Creates a .png file output including the green mask for POI billboards.  The Orbitron font does not produce images with the "blurred" effect that is apparent in the original POI .png files, if anyone know an extra processing step, if it is even required anymore, please point me in the right direction.

### CODE REVIEW

**Comment by timGerken** [comment]
Hi @elitemn, can you rebase your clone so only the POI Maker utility change(s) are included.

The git commands should be something like:
    git rebase -I Microsoft/master
    // mark the commits you want with "pick"
    // mark other commits as "fixup"
    git push -f

Adding Neeraj as well :). @NeerajW

**Comment by timGerken** [comment]
In general, the start of the functionality is there.
As it stands now, two things are noticeable:
1) the glyph ([]\\\\\) needs to be shifted to the right so it is left-aligned with the title text
2) the smaller text (and to some extend, the larger text) does not appear solid.

I think we need to figure out how the "fuzzy effect" in the original GE was done. I'll send out an email or two after lunch to see what I can dig up.

**Comment by timGerken** [comment]
Apparently the blurring effect was done with a Photoshop action macro. I have the code, but no real way to incorporate it directly into your tool.

**Comment by elitemn** [comment]
Hi Tim,

Interesting, can we use c# image libraries to produce a similar effect (maybe when converting text to image). I’ll have more time to look a it late next week. Before I go there, time to ask a question: 

Is the effect worth the effort?

If no, replace all current POI banners with simpler implementation (perhaps a normal windows font, no mask). This would make it easy to create new content.

If yes, figure out a way to exactly reproduce within the POI maker tool. Perhaps using the code you have as a start (there has to be a way)

What is your opinion?

Or else perhaps they had an automated way to do this by executing a main macro that we could borrow?

Just a few ideas, let me know what you think.

**Comment by timGerken** [comment]
That is a good question and worthy of discussion.
At this point, the idea is that we would periodically re-publish GE to the store as new and interesting features are added. I'd like to maintain as much visual consistency and fidelity as possible with the original version. I've attached (I believe) a zip file containing the "code" received from the team. I'm not much of an expert on Photoshop, however.

**Comment by timGerken** [comment]
[this](http://www.codeproject.com/Articles/13444/Creating-fancy-text-effects-with-C) looks promising.

**Comment by timGerken** [comment]
@elitemn, I've been digging deep into my past (former GDI tester) and playing around with paths. I'll issue a PR into your fork soon for you to take a look.

**Comment by timGerken** [comment]
@elitemn, I haven't been able to figure out a legit git way to fork your fork and issue a PR from me to you, so I'm attaching the two files I changed. Let me know what you think.

[blurText.zip](https://github.com/Microsoft/GalaxyExplorer/files/503907/blurText.zip)

**Pull request closed without merging**
